version: "3.8"
services:
    shopit:
        container_name: shopit
        restart: always
        build: .
        ports:
            - "4000:4000"
        links:
            - noSQLDB
            - sqlDB
        depends_on:
            - noSQLDB
            - sqlDB
    noSQLDB:
        container_name: noSQLDB
        image: mongo:latest
        restart: always
        volumes:
            - nosql-data:/data/db
        ports:
            - "27017:27017"
    sqlDB:
        container_name: sqlDB
        image: postgres:latest
        restart: always
        volumes:
            - sql-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: shopit
            POSTGRES_USER: shopit
            POSTGRES_PASSWORD: computadorar
    adminer:
        container_name: adminer
        image: adminer
        restart: always
        ports:
            - 8080:8080
volumes:
    nosql-data:
    sql-data:
