@hostname = localhost
@port = 4000
@baseUrl = api/v1
@host = {{hostname}}:{{port}}/{{baseUrl}}
@contentType = application/json
@csrf = RwYQtC9A-KetMVAXmheCepbVyVqb244XNYcc

# Sign-in user view
GET http://{{host}}/users/sign-in
Content-Type: {{contentType}}

###

# Sign-in user
POST http://{{host}}/users/sign-in
Content-Type: {{contentType}}
CSRF-Token: {{csrf}}

###

# Sign-up user
POST http://{{host}}/users/sign-up
Content-Type: {{contentType}}
CSRF-Token: {{csrf}}

{
    "email": "victorio.matteucci@gmail.com"
}
