@hostname = localhost
@port = 4000
@baseUrl = api/v1
@host = {{hostname}}:{{port}}/{{baseUrl}}
@contentType = application/json
@csrf = EgZVIjbQ-s8Jg4TsDCD9Dql3FO7vKH_IlL-E

# Login user
GET http://{{host}}/users/login
Content-Type: {{contentType}}

###

POST http://{{host}}/users/login
Content-Type: {{contentType}}
CSRF-Token: {{csrf}}
