@hostname = localhost
@port = 4000
@baseUrl = api/v1
@host = {{hostname}}:{{port}}/{{baseUrl}}
@contentType = application/json
@csrf = gl9GJekd--eDuGxoxKmcHs_ZtnRlZn4Hy47Q

# Sign-in user view
GET http://{{host}}/users/sign-in
Content-Type: {{contentType}}

###

# Sign-in user
POST http://{{host}}/users/sign-in
Content-Type: {{contentType}}
CSRF-Token: {{csrf}}

###

# Sign-up user
POST http://{{host}}/users/sign-up
Content-Type: {{contentType}}
CSRF-Token: {{csrf}}

{
    "email": "victorio.matteucci.shopit@gmail.com",
    "password": "computadorar",
    "firstName": "vitto",
    "lastName": "matt",
    "role": "admin"
}

###

# Forgot password
POST http://{{host}}/users/forgot-password
Content-Type: {{contentType}}
CSRF-Token: {{csrf}}

{
    "email": "victorio.matteucci.shopit@gmail.com"
}

###

# Reset password
POST http://{{host}}/users/reset-password
Content-Type: {{contentType}}
CSRF-Token: {{csrf}}

{
    "email": "victorio.matteucci.shopit@gmail.com",
    "newPassword": "computadorar",
    "resetPasswordToken": "97fdd9ee8324e29647c0818cf806bb2aef872ad81436d80ee2527575d71b979f"
}
