@hostname = localhost
@port = 4000
@baseUrl = api/v1
@host = {{hostname}}:{{port}}/{{baseUrl}}
@contentType = application/json


# Get all products
GET http://{{host}}/products

###

# Get product by id
GET http://{{host}}/products/4681127e-fe12-4d13-bcda-21cdcf4a7d57

###

# Create product
POST http://{{host}}/products
Content-Type: {{contentType}}

{
    "title": "title",
    "description": "description",
    "price": 1.11,
    "ratings": 3,
    "imageUrl": "https://unsplash.com/photos/jcNuyQjgYPs",
    "category": "Electronics",
    "stock": 2
}

###

# Delete product by id
DELETE http://{{host}}/products/4681127e-fe12-4d13-bcda-21cdcf4a7d57

###

# Update product by id
PUT http://{{host}}/products/4681127e-fe12-4d13-bcda-21cdcf4a7d57
Content-Type: {{contentType}}

{
    "title": "title*",
    "description": "description*",
    "price": 2.22,
    "ratings": 4,
    "imageUrl": "https://unsplash.com/photos/jcNuyQjgYPs",
    "category": "Electronics",
    "stock": 3
}